import 'package:flutter/material.dart';
import 'package:flutterapp/parcialjeiderapp/generatedpagowidget/generated/GeneratedMtododepagoWidget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedpagowidget/generated/GeneratedJeiderWidget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedpagowidget/generated/GeneratedGroup29Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedpagowidget/generated/GeneratedGroup28Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedpagowidget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedpagowidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedpagowidget/generated/GeneratedHolaWidget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedpagowidget/generated/GeneratedGroup26Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedpagowidget/generated/GeneratedGroup31Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedpagowidget/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedpagowidget/generated/GeneratedGroup27Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedpagowidget/generated/GeneratedGroup30Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedpagowidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedpagowidget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedpagowidget/generated/GeneratedGroup32Widget.dart';

/* Frame Pago
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPagoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 162, 156, 156),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 844.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 750.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 94.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 311.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 68.0,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 181.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 68.0,
                child: GeneratedGroup11Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 68.0,
                child: GeneratedGroup12Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 22.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 33.0,
                child: GeneratedHolaWidget(),
              ),
              Positioned(
                left: 76.0,
                top: 22.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 33.0,
                child: GeneratedJeiderWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 209.1134033203125,
                right: null,
                bottom: null,
                width: 359.0,
                height: 73.8865966796875,
                child: GeneratedGroup29Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 139.54638671875,
                child: GeneratedGroup27Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 344.0,
                height: 129.0,
                child: GeneratedGroup28Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 14.0,
                child: GeneratedMtododepagoWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 436.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 47.0,
                child: GeneratedGroup30Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 47.0,
                child: GeneratedGroup31Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 47.0,
                child: GeneratedGroup32Widget(),
              ),
              Positioned(
                left: 97.0,
                top: 673.0,
                right: null,
                bottom: null,
                width: 207.0,
                height: 43.0,
                child: GeneratedGroup26Widget(),
              )
            ]),
      ),
    ));
  }
}
