import 'package:flutter/material.dart';
import 'package:flutterapp/parcialjeiderapp/generatedbarbeariaswidget1/generated/GeneratedGroup15Widget1.dart';
import 'package:flutterapp/parcialjeiderapp/generatedbarbeariaswidget1/generated/GeneratedHolaWidget5.dart';
import 'package:flutterapp/parcialjeiderapp/generatedbarbeariaswidget1/generated/GeneratedGroup8Widget1.dart';
import 'package:flutterapp/parcialjeiderapp/generatedbarbeariaswidget1/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedbarbeariaswidget1/generated/GeneratedGroup17Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedbarbeariaswidget1/generated/GeneratedRectangle2Widget7.dart';
import 'package:flutterapp/parcialjeiderapp/generatedbarbeariaswidget1/generated/GeneratedJeiderWidget5.dart';
import 'package:flutterapp/parcialjeiderapp/generatedbarbeariaswidget1/generated/GeneratedGroup14Widget1.dart';
import 'package:flutterapp/parcialjeiderapp/generatedbarbeariaswidget1/generated/GeneratedGroup35Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedbarbeariaswidget1/generated/GeneratedGroup13Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedbarbeariaswidget1/generated/GeneratedGroup16Widget1.dart';
import 'package:flutterapp/parcialjeiderapp/generatedbarbeariaswidget1/generated/GeneratedGroup19Widget1.dart';

/* Frame barbearias
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBarbeariasWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 162, 156, 156),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 844.0,
                child: GeneratedRectangle2Widget7(),
              ),
              Positioned(
                left: 15.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 30.0,
                child: GeneratedHolaWidget5(),
              ),
              Positioned(
                left: 76.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 33.0,
                child: GeneratedJeiderWidget5(),
              ),
              Positioned(
                left: 9.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 165.0,
                child: GeneratedGroup8Widget1(),
              ),
              Positioned(
                left: 200.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 165.0,
                child: GeneratedGroup13Widget(),
              ),
              Positioned(
                left: 9.0,
                top: 645.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 165.0,
                child: GeneratedGroup18Widget(),
              ),
              Positioned(
                left: 200.0,
                top: 645.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 165.0,
                child: GeneratedGroup19Widget1(),
              ),
              Positioned(
                left: 9.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 165.0,
                child: GeneratedGroup14Widget1(),
              ),
              Positioned(
                left: 200.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 165.0,
                child: GeneratedGroup15Widget1(),
              ),
              Positioned(
                left: 9.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 165.0,
                child: GeneratedGroup16Widget1(),
              ),
              Positioned(
                left: 200.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 165.0,
                child: GeneratedGroup17Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 750.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 94.0,
                child: GeneratedGroup35Widget(),
              )
            ]),
      ),
    ));
  }
}
