import 'package:flutter/material.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedGroup28Widget1.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedJeiderWidget4.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedProdutoWidget1.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedRectangle6Widget8.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedRectangle2Widget4.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedQueBarberialegastaravisitarWidget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedGroup10Widget4.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedProductosmasvendidosWidget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedGroup11Widget4.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedServiciosWidget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedBarberasmasfrecuentesWidget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedRectangle7Widget4.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedHolaWidget4.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedtelainicialwidget/generated/GeneratedProdutoWidget.dart';

/* Frame Tela Inicial
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTelaInicialWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 162, 156, 156),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 844.0,
                child: GeneratedRectangle2Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 750.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 94.0,
                child: GeneratedRectangle7Widget4(),
              ),
              Positioned(
                left: 21.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 33.0,
                child: GeneratedHolaWidget4(),
              ),
              Positioned(
                left: 82.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 33.0,
                child: GeneratedJeiderWidget4(),
              ),
              Positioned(
                left: 10.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 369.0,
                height: 90.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 179.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 27.0,
                child: GeneratedServiciosWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 24.0,
                child: GeneratedBarberasmasfrecuentesWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 46.0,
                child: GeneratedRectangle6Widget8(),
              ),
              Positioned(
                left: 21.0,
                top: 75.0,
                right: null,
                bottom: null,
                width: 268.0,
                height: 24.0,
                child: GeneratedQueBarberialegastaravisitarWidget(),
              ),
              Positioned(
                left: null,
                top: 214.0,
                right: 248.0,
                bottom: 580.0,
                width: 44.0,
                height: null,
                child: GeneratedGroup5Widget(),
              ),
              Positioned(
                left: null,
                top: 213.0,
                right: 103.0,
                bottom: 580.0,
                width: 64.0,
                height: null,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: null,
                top: 215.0,
                right: 14.0,
                bottom: 579.0,
                width: 75.0,
                height: null,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: null,
                top: 214.0,
                right: 314.0,
                bottom: 580.0,
                width: 53.0,
                height: null,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: null,
                top: 214.0,
                right: 182.0,
                bottom: 579.0,
                width: 44.0,
                height: null,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 573.0,
                height: 168.0,
                child: GeneratedGroup8Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 545.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 190.0,
                child: GeneratedProdutoWidget(),
              ),
              Positioned(
                left: 179.0,
                top: 545.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 192.0,
                child: GeneratedProdutoWidget1(),
              ),
              Positioned(
                left: 22.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 217.0,
                height: 24.0,
                child: GeneratedProductosmasvendidosWidget(),
              ),
              Positioned(
                left: 301.0,
                top: 760.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 68.0,
                child: GeneratedGroup10Widget4(),
              ),
              Positioned(
                left: 179.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 68.0,
                child: GeneratedGroup11Widget4(),
              ),
              Positioned(
                left: 52.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 68.0,
                child: GeneratedGroup28Widget1(),
              )
            ]),
      ),
    ));
  }
}
