import 'package:flutter/material.dart';
import 'package:flutterapp/parcialjeiderapp/generatedsalonwidget/generated/GeneratedGroup14Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedsalonwidget/generated/GeneratedGroup27Widget1.dart';
import 'package:flutterapp/parcialjeiderapp/generatedsalonwidget/generated/GeneratedRectangle7Widget3.dart';
import 'package:flutterapp/parcialjeiderapp/generatedsalonwidget/generated/GeneratedGroup11Widget3.dart';
import 'package:flutterapp/parcialjeiderapp/generatedsalonwidget/generated/GeneratedGroup12Widget3.dart';
import 'package:flutterapp/parcialjeiderapp/generatedsalonwidget/generated/GeneratedSobreWidget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedsalonwidget/generated/GeneratedEsunestablecimientodondeloshombrespuedenrelajarseysocia.dart';
import 'package:flutterapp/parcialjeiderapp/generatedsalonwidget/generated/GeneratedPexelsdmitryzvolskiy15708073Widget.dart';
import 'package:flutterapp/parcialjeiderapp/generatedsalonwidget/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/parcialjeiderapp/generatedsalonwidget/generated/GeneratedJeiderWidget3.dart';
import 'package:flutterapp/parcialjeiderapp/generatedsalonwidget/generated/Generated\$45000Widget3.dart';
import 'package:flutterapp/parcialjeiderapp/generatedsalonwidget/generated/GeneratedAgendaWidget5.dart';
import 'package:flutterapp/parcialjeiderapp/generatedsalonwidget/generated/GeneratedHolaWidget3.dart';
import 'package:flutterapp/parcialjeiderapp/generatedsalonwidget/generated/GeneratedRectangle2Widget3.dart';
import 'package:flutterapp/parcialjeiderapp/generatedsalonwidget/generated/GeneratedGroup10Widget3.dart';
import 'package:flutterapp/parcialjeiderapp/generatedsalonwidget/generated/GeneratedGroup24Widget.dart';

/* Frame salon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSalonWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 162, 156, 156),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 844.0,
                child: GeneratedRectangle2Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 750.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 94.0,
                child: GeneratedRectangle7Widget3(),
              ),
              Positioned(
                left: 304.0,
                top: 760.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 68.0,
                child: GeneratedGroup10Widget3(),
              ),
              Positioned(
                left: 181.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 68.0,
                child: GeneratedGroup11Widget3(),
              ),
              Positioned(
                left: 29.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 68.0,
                child: GeneratedGroup12Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 214.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 43.0,
                child: GeneratedGroup14Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 214.0,
                child: GeneratedPexelsdmitryzvolskiy15708073Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 30.0,
                child: GeneratedHolaWidget3(),
              ),
              Positioned(
                left: 76.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 33.0,
                child: GeneratedJeiderWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 27.0,
                child: GeneratedSobreWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 27.0,
                child: GeneratedAgendaWidget5(),
              ),
              Positioned(
                left: 17.0,
                top: 403.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 231.0,
                child: GeneratedGroup27Widget1(),
              ),
              Positioned(
                left: 99.0,
                top: 693.0,
                right: null,
                bottom: null,
                width: 207.0,
                height: 43.0,
                child: GeneratedGroup1Widget1(),
              ),
              Positioned(
                left: 151.0,
                top: 649.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 32.0,
                child: Generated$45000Widget3(),
              ),
              Positioned(
                left: 260.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 16.0,
                child: GeneratedGroup24Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 62.0,
                child:
                    GeneratedEsunestablecimientodondeloshombrespuedenrelajarseysocia(),
              )
            ]),
      ),
    ));
  }
}
